const menu = [
    {
        id: 1,
        title: 'Golf Ball',
        category: 'Golf Equipment',
        img: './images/equipment/ball1.jpg',
        alt_tag: 'Golf Ball by Beaver Sports',
    },
    {
        id: 2,
        title: 'Golf Ball',
        category: 'Golf Equipment',
        img: './images/equipment/ball2.jpg',
        alt_tag: 'Golf Ball by Beaver Sports',
    },
    {
        id: 3,
        title: 'Golf Mat',
        category: 'Golf Equipment',
        img: './images/equipment/golf_mat.jpg',
        alt_tag: 'Golf Mat by Beaver Sports',
    },
    {
        id: 4,
        title: 'Ball Dispenser',
        category: 'Machine',
        img: './images/machine/ball_dispenser.jpg',
        alt_tag: 'Ball Dispenser by Beaver Sports',
    },
    {
        id: 5,
        title: 'Tee Up Machine',
        category: 'Machine',
        img: './images/machine/t_up.jpg',
        alt_tag: 'Tee Up Machine by Beaver Sports',
    },
    {
        id: 6,
        title: 'Blowing Machine',
        category: 'Machine',
        img: './images/machine/blow_machine.GIF',
        alt_tag: 'Blowing Machine by Beaver Sports',
    },
    {
        id: 7,
        title: 'Artificial Turf 1',
        category: 'Artificial Turf',
        img: './images/turf/turf1.jpg',
        alt_tag: 'Artificial Turf by Beaver Sports',
    },
    {
        id: 8,
        title: 'Artificial Turf 2',
        category: 'Artificial Turf',
        img: './images/turf/turf2.jpg',
        alt_tag: 'Artificial Turf by Beaver Sports',
    },
    {
        id: 9,
        title: 'Artificial Turf 3',
        category: 'Artificial Turf',
        img: './images/turf/turf3.jpg',
        alt_tag: 'Artificial Turf by Beaver Sports',
    },
    {
        id: 10,
        title: 'Ball Collector',
        category: 'Golf Equipment',
        img: './images/equipment/ball_collector.jpg',
        alt_tag: 'Ball Collector by Beaver Sports',
    },
    {
        id: 11,
        title: 'Buggy',
        category: 'Buggy',
        img: './images/buggy/buggy1.jpg',
        alt_tag: 'Buggy by Beaver Sports',
    },
    {
        id: 12,
        title: 'Buggy',
        category: 'Buggy',
        img: './images/buggy/buggy2.jpg',
        alt_tag: 'Buggy by Beaver Sports',
    },

];
export default menu;